packages:
  - www
  - mcp-server

catalog:
  '@modelcontextprotocol/sdk': ^1.18.1
  '@radix-ui/react-accordion': ^1.2.2
  '@radix-ui/react-alert-dialog': ^1.1.4
  '@radix-ui/react-aspect-ratio': ^1.1.1
  '@radix-ui/react-avatar': ^1.1.2
  '@radix-ui/react-checkbox': ^1.1.3
  '@radix-ui/react-collapsible': ^1.1.2
  '@radix-ui/react-context-menu': ^2.2.4
  '@radix-ui/react-dialog': ^1.1.4
  '@radix-ui/react-dropdown-menu': ^2.1.4
  '@radix-ui/react-hover-card': ^1.1.4
  '@radix-ui/react-label': ^2.1.1
  '@radix-ui/react-menubar': ^1.1.4
  '@radix-ui/react-navigation-menu': ^1.2.3
  '@radix-ui/react-popover': ^1.1.4
  '@radix-ui/react-progress': ^1.1.1
  '@radix-ui/react-radio-group': ^1.2.2
  '@radix-ui/react-scroll-area': ^1.2.2
  '@radix-ui/react-select': ^2.1.4
  '@radix-ui/react-separator': ^1.1.1
  '@radix-ui/react-slider': ^1.2.2
  '@radix-ui/react-slot': ^1.1.1
  '@radix-ui/react-switch': ^1.1.2
  '@radix-ui/react-tabs': ^1.1.2
  '@radix-ui/react-toast': ^1.2.4
  '@radix-ui/react-toggle': ^1.1.1
  '@radix-ui/react-toggle-group': ^1.1.1
  '@radix-ui/react-tooltip': ^1.1.6
  '@tailwindcss/postcss': ^4.1.13
  '@types/node': ^24.5.2
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@types/ws': ^8.5.12
  autoprefixer: ^10.4.21
  babel-plugin-react-compiler: ^19.1.0-rc.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commander: ^14.0.1
  lucide-react: ^0.544.0
  mcp-handler: ^1.0.2
  next: 15.5.1-canary.30
  postcss: ^8.5.6
  react: 19.2.0-canary-de5a1b20-20250905
  react-dom: 19.2.0-canary-de5a1b20-20250905
  tailwind-merge: ^2.5.5
  tailwindcss: ^4.1.13
  tw-animate-css: ^1.3.8
  typescript: ^5.0.0
  ws: ^8.18.3
  zod: ^3.22.4

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
