name: Test Release

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-release:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4

      # Install bun for preinstall script (bunx only-allow pnpm)
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # Install pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 10.18.3
      
      # Install dependencies
      - run: pnpm install
      
      # Run the full release test suite
      - name: Run Release Tests
        run: ./scripts/test-release.sh
